production:
  FB_ID: "212169366043011"
  FB_SECRET: "719fdbcce2f46dbf64a10573ea2c2309"

production:
  STRIPE_PUBLISHABLE_KEY: "pk_test_6J4hSnQnUE6rYgZLpWMTTa5I"
  STRIPE_SECRET_KEY:  "sk_test_7oEByfgJxpcB0R1FO86HKtqV"
