production:
  FB_ID: "212169366043011"
  FB_SECRET: "719fdbcce2f46dbf64a10573ea2c2309"

production:
  STRIPE_PUBLISHABLE_KEY: "pk_live_019ASlndT7ZwtX7WI8Iw2si0"
  STRIPE_SECRET_KEY:  "sk_test_7oEByfgJxpcB0R1FO86HKtqV"

development:
  STRIPE_PUBLISHABLE_KEY: "pk_test_LE2sFUPuGOnxsuQXTU1Qrs2v"
  STRIPE_SECRET_KEY: "sk_test_rkDpjxAzkk25bjFfUHJV6aY7"
