production:
  FB_SECRET: "719fdbcce2f46dbf64a10573ea2c2309"
  FB_ID: "212169366043011"
  STRIPE_PUBLISHABLE_KEY: "pk_test_LE2sFUPuGOnxsuQXTU1Qrs2v"
  STRIPE_SECRET_KEY:  "sk_test_rkDpjxAzkk25bjFfUHJV6aY7"
  # GOOGLE_PLACES_KEY: "AIzaSyAKb0ljZqJ7aHL_XwB8kqobd679C9Rly9o"
  GOOGLE_PLACES_KEY: "AIzaSyCFnDXN6G_8yyB0KjcfV4h0D-_LsnCCX5c"

development:
  STRIPE_PUBLISHABLE_KEY: "pk_test_LE2sFUPuGOnxsuQXTU1Qrs2v"
  STRIPE_SECRET_KEY: "sk_test_rkDpjxAzkk25bjFfUHJV6aY7"
  GOOGLE_PLACES_KEY: "AIzaSyBsCPWcOcjt6XbMm6MOsRretGjkgclnWZk"
  # GOOGLE_PLACES_KEY: "AIzaSyCGpNG33CbdsPUou2fE9iYeIDAPGZ8vwUY"
